//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apolices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apolices()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
        }
    
        public System.Guid IDApolice { get; set; }
        public string Apolice { get; set; }
        public string Companhia { get; set; }
        public string Ramo { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public System.DateTime DataTermo { get; set; }
        public bool Renovavel { get; set; }
        public double Valor { get; set; }
        public double Premio { get; set; }
        public string Certificado { get; set; }
        public string Observacoes { get; set; }
        public double DescontoFuncionario { get; set; }
        public double DescontoEmpresa { get; set; }
        public bool Percentagem { get; set; }
        public bool PagoVencimento { get; set; }
        public bool PagoMesFerias { get; set; }
        public bool PagoSubsidioNatal { get; set; }
        public bool PagoSubsidioFerias { get; set; }
        public bool PagoExtraordinario { get; set; }
        public string Moeda { get; set; }
        public string TipoEntidadeCCT { get; set; }
        public string EntidadeCCT { get; set; }
        public bool DiasTrabalhados { get; set; }
    
        public virtual Moedas Moedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}
