//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonificacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bonificacoes()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
        }
    
        public string Bonificacao { get; set; }
        public string Descricao { get; set; }
        public short Natureza { get; set; }
        public short TipoVigencia { get; set; }
        public float PercBonificacao { get; set; }
        public bool AfectaFuncionario { get; set; }
        public bool AfectaEmpresa { get; set; }
        public string CodigoSegSocial { get; set; }
        public Nullable<bool> AfectaIT { get; set; }
        public Nullable<bool> AfectaIMS { get; set; }
        public double ValorBonificacao { get; set; }
        public bool AplicaIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}
