//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categorias()
        {
            this.CategoriasEscaloes = new HashSet<CategoriasEscaloes>();
            this.Funcionarios = new HashSet<Funcionarios>();
        }
    
        public string Categoria { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<float> ValSeguro { get; set; }
        public string CodigoQP { get; set; }
        public string Carreira { get; set; }
        public string CategoriaDL12A2008 { get; set; }
        public string CodRegimeLVCR { get; set; }
        public string ConteudoFuncional { get; set; }
        public Nullable<bool> DL12A2008 { get; set; }
        public Nullable<int> GrauComplexidade { get; set; }
        public string Grupo { get; set; }
        public Nullable<bool> Inactiva { get; set; }
        public string NivelTransicao { get; set; }
        public Nullable<float> NumTotalMeses { get; set; }
        public Nullable<bool> Transicao { get; set; }
        public int NumPontos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasEscaloes> CategoriasEscaloes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}
