//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratosTrabalho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratosTrabalho()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
        }
    
        public string Contrato { get; set; }
        public string Descricao { get; set; }
        public Nullable<byte> PerExperimental { get; set; }
        public string CodContratoSegSocial { get; set; }
        public string Bonificacao { get; set; }
        public string CodSegSocial { get; set; }
        public bool PercContratoMenos7Dias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}
