//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estabelecimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estabelecimentos()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
        }
    
        public string Estabelecimento { get; set; }
        public string Nome { get; set; }
        public string Morada { get; set; }
        public string Localidade { get; set; }
        public string CodPostal1 { get; set; }
        public string CodPostal2 { get; set; }
        public string Distrito { get; set; }
        public string CodDistrito { get; set; }
        public string CodConcelho { get; set; }
        public string CodFreguesia { get; set; }
        public string CodIRC { get; set; }
        public string Concelho { get; set; }
        public string Freguesia { get; set; }
        public string Telefone { get; set; }
        public string IndTelefone { get; set; }
        public string Fax { get; set; }
        public string IndFax { get; set; }
        public Nullable<short> NumEmpregados { get; set; }
        public string RepFinancas { get; set; }
        public string Contribuinte { get; set; }
        public string CAE { get; set; }
        public string CodCAE { get; set; }
        public string SegSocial { get; set; }
        public string NumSegSocial { get; set; }
        public string CodigoCGA { get; set; }
        public string NumCGA { get; set; }
        public string NomeContactoSS { get; set; }
        public string CargoContactoSS { get; set; }
        public string TelfContactoSS { get; set; }
        public string CodigoQP { get; set; }
        public string CodEstabSS { get; set; }
        public bool OrganizServicosSHST { get; set; }
        public byte ActividadeSegHigiene { get; set; }
        public byte ActividadeSaude { get; set; }
        public string NomeContactoSHST { get; set; }
        public string TelefonePrincContactoSHST { get; set; }
        public string TelefoneAltContactoSHST { get; set; }
        public string FaxContactoSHST { get; set; }
        public string EmailContactoSHST { get; set; }
        public string NomeMutua { get; set; }
        public string EpigrafeMutua { get; set; }
        public string ContaBancaria { get; set; }
        public string SegHigieneTipoEntidade { get; set; }
        public string SegHigieneEntidade { get; set; }
        public string SaudeTipoEntidade { get; set; }
        public string SaudeEntidade { get; set; }
        public string EpigrafeIT { get; set; }
        public string Epigrafe { get; set; }
        public Nullable<short> Diploma { get; set; }
        public string IDEstabelecimento { get; set; }
        public bool Sede { get; set; }
        public string PrimeiroNome { get; set; }
        public string PrimeiroApelido { get; set; }
        public string SegundoApelido { get; set; }
        public string NIFContactoSS { get; set; }
        public string Email { get; set; }
        public string CalendarioTrabalho { get; set; }
        public bool FeriasFeriados { get; set; }
        public string Ministerio { get; set; }
        public string Organismo { get; set; }
        public string TipoLancamento { get; set; }
    
        public virtual RepFinancas RepFinancas1 { get; set; }
        public virtual SegSocial SegSocial1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}
