//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncAgregadoFamiliar
    {
        public string Funcionario { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public bool Deficiente { get; set; }
        public Nullable<bool> Estudante { get; set; }
        public Nullable<byte> TipoAfinidade { get; set; }
        public string NumBI { get; set; }
        public Nullable<System.DateTime> DataValidadeBI { get; set; }
        public string Agregado { get; set; }
        public bool Activo { get; set; }
        public Nullable<float> PercIncapacidade { get; set; }
        public Nullable<bool> Mobilidade { get; set; }
        public Nullable<short> NumPessoasDeConvivencia { get; set; }
        public Nullable<bool> ConvivenciaExclusiva { get; set; }
        public string NIF { get; set; }
        public string EntidadePatronal { get; set; }
        public bool AlargamentoAbFamilia { get; set; }
        public string AnoEscolar { get; set; }
        public bool AproveitamentoEscolar { get; set; }
        public Nullable<bool> ComprovativoEstudo { get; set; }
        public string Curso { get; set; }
        public Nullable<System.DateTime> DataValidadeADSE { get; set; }
        public bool DependenciaTerceiraPessoa { get; set; }
        public string EstabEnsino { get; set; }
        public Nullable<int> GrauEnsino { get; set; }
        public System.Guid idMembroAgregado { get; set; }
        public string NumADSE { get; set; }
    
        public virtual Funcionarios Funcionarios { get; set; }
    }
}
