//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionarios()
        {
            this.FuncAgregadoFamiliar = new HashSet<FuncAgregadoFamiliar>();
            this.FuncHorarios = new HashSet<FuncHorarios>();
            this.FuncInfFerias = new HashSet<FuncInfFerias>();
            this.FuncInfNatal = new HashSet<FuncInfNatal>();
            this.FuncInfSFerias = new HashSet<FuncInfSFerias>();
            this.FuncFormasPagamento = new HashSet<FuncFormasPagamento>();
            this.FuncRem = new HashSet<FuncRem>();
        }
    
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public string Localidade { get; set; }
        public string CodPostal1 { get; set; }
        public string CodPostal2 { get; set; }
        public string Naturalidade { get; set; }
        public string Distrito { get; set; }
        public string Nacionalidade { get; set; }
        public string Telefone { get; set; }
        public string EstadoCivil { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public Nullable<System.DateTime> DataAdmissao { get; set; }
        public Nullable<System.DateTime> DataReadmissao { get; set; }
        public Nullable<System.DateTime> DataFimContrato { get; set; }
        public string Categoria { get; set; }
        public string Profissao { get; set; }
        public string Qualificacao { get; set; }
        public Nullable<System.DateTime> DataQualif { get; set; }
        public string Habilitacao { get; set; }
        public Nullable<int> TipoContrato { get; set; }
        public Nullable<System.DateTime> DataDemissao { get; set; }
        public Nullable<System.DateTime> DataPromocao { get; set; }
        public string MotivoPromocao { get; set; }
        public Nullable<float> HorasSemana { get; set; }
        public string CodEstabelecimento { get; set; }
        public string Situacao { get; set; }
        public string SituacaoQP { get; set; }
        public string NumBI { get; set; }
        public string LocalEmBi { get; set; }
        public Nullable<System.DateTime> DataEmBi { get; set; }
        public string CartaConducao { get; set; }
        public Nullable<double> Vencimento { get; set; }
        public Nullable<System.DateTime> DataUltAumento { get; set; }
        public string MotivoAumento { get; set; }
        public string Notas { get; set; }
        public string NumContr { get; set; }
        public string CodRepFinancas { get; set; }
        public string CodIRS { get; set; }
        public Nullable<short> TotalDependentes { get; set; }
        public Nullable<short> TotalDepDeficientes { get; set; }
        public bool ConjugeDef { get; set; }
        public Nullable<float> IRSFixo { get; set; }
        public string NomeConjuge { get; set; }
        public string CodSegSocial { get; set; }
        public string NumBeneficiario { get; set; }
        public string CodSindicato { get; set; }
        public string NumSindicato { get; set; }
        public Nullable<short> TipoProcessamento { get; set; }
        public Nullable<System.DateTime> DataUltProcessamento { get; set; }
        public Nullable<System.DateTime> DataSubsFerias { get; set; }
        public Nullable<short> MesSubsFerias { get; set; }
        public Nullable<System.DateTime> DataSubsNatal { get; set; }
        public Nullable<short> TurnosTaxa { get; set; }
        public Nullable<short> TurnosDia { get; set; }
        public Nullable<short> SubsAlim1 { get; set; }
        public Nullable<short> SubsAlim2 { get; set; }
        public Nullable<double> ValorSubsAlim { get; set; }
        public Nullable<double> ValorSubsEsp { get; set; }
        public Nullable<float> DiasSubsNatal { get; set; }
        public Nullable<float> DiasSubsFerias { get; set; }
        public Nullable<float> SalHora { get; set; }
        public Nullable<float> HoraEntradaM { get; set; }
        public Nullable<float> HoraSaidaM { get; set; }
        public Nullable<float> HoraEntradaT { get; set; }
        public Nullable<float> HoraSaidaT { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> DataInspMedica { get; set; }
        public string DescricaoInspMedica { get; set; }
        public string CodBancoEmpr { get; set; }
        public string Morada { get; set; }
        public string Email { get; set; }
        public string Periodo { get; set; }
        public string CodDepartamento { get; set; }
        public Nullable<short> NumPeriodoProcessado { get; set; }
        public string Instrumento { get; set; }
        public bool SubsNatalProcessado { get; set; }
        public Nullable<double> VencimentoMensal { get; set; }
        public Nullable<double> DiuturnidadeMensal { get; set; }
        public Nullable<double> Diuturnidades { get; set; }
        public bool NumHorasSemInstrumentos { get; set; }
        public bool PertenceOrgaosSoc { get; set; }
        public Nullable<System.DateTime> DataProximaDiuturnidade { get; set; }
        public string Telemovel { get; set; }
        public Nullable<double> LimiteContribuicoesSegSocial { get; set; }
        public string CGA { get; set; }
        public string NumCGA { get; set; }
        public string NomeCGA { get; set; }
        public Nullable<float> RegTmpPercAcresCGA { get; set; }
        public Nullable<int> NumDiuturnidadesCGA { get; set; }
        public string NivelRemCGA { get; set; }
        public string RegTmpSituacaoCGA { get; set; }
        public Nullable<float> RegTmpNumHorasCGA { get; set; }
        public Nullable<System.DateTime> UltimaProgressao { get; set; }
        public Nullable<float> DiasSubsNatalJaPagos { get; set; }
        public string TipoPessoal { get; set; }
        public short UltimoAnoProcessado { get; set; }
        public short DomicilioFiscal { get; set; }
        public string Extensao { get; set; }
        public short CodSituacaoQP { get; set; }
        public string NomeAbreviado { get; set; }
        public string Contrato { get; set; }
        public Nullable<System.DateTime> DataAvisoPrevio { get; set; }
        public Nullable<int> PeriodoExp { get; set; }
        public string MotivoSaida { get; set; }
        public Nullable<System.DateTime> DataValidadeCarta { get; set; }
        public Nullable<System.DateTime> DataValidadeBI { get; set; }
        public string Concelho { get; set; }
        public string Freguesia { get; set; }
        public Nullable<System.DateTime> DataIniProfissao { get; set; }
        public Nullable<System.DateTime> DataHabilitacao { get; set; }
        public string CargoPrincipal { get; set; }
        public string RegimeTrab { get; set; }
        public Nullable<double> Altura { get; set; }
        public string GrupoSanguineo { get; set; }
        public string DeficienciasFisicas { get; set; }
        public string OutrasDadosFisicos { get; set; }
        public string DeficienciasCronicas { get; set; }
        public string DoencasHereditarias { get; set; }
        public string Cirurgias { get; set; }
        public string NomeDistrito { get; set; }
        public string NomeConcelho { get; set; }
        public Nullable<System.Guid> IdGDOC { get; set; }
        public string NomeFreguesia { get; set; }
        public Nullable<decimal> VencimentoLiquidoEstimado { get; set; }
        public string Moeda { get; set; }
        public string EpigrafeAT { get; set; }
        public string GrupoCotizacao { get; set; }
        public string Bonificacao { get; set; }
        public string IniciaisNomeSegSocial { get; set; }
        public Nullable<float> PercIncapacidade { get; set; }
        public Nullable<bool> MobilidadeReduzida { get; set; }
        public Nullable<double> ReducaoIrregularidades { get; set; }
        public Nullable<double> GastosDedutiveis { get; set; }
        public Nullable<double> PensaoConjuge { get; set; }
        public Nullable<double> PensaoFilhos { get; set; }
        public Nullable<bool> MobilidadeGeografica { get; set; }
        public Nullable<bool> ProlongacaoActLaboral { get; set; }
        public Nullable<double> VencimentoDiario { get; set; }
        public Nullable<short> TipoCalculoVencimento { get; set; }
        public Nullable<bool> VencimentoConjSupLimite { get; set; }
        public string NumPassaporte { get; set; }
        public string LocalEmPassaporte { get; set; }
        public Nullable<System.DateTime> DataEmPassaporte { get; set; }
        public Nullable<System.DateTime> DataValidadePassaporte { get; set; }
        public string NumIE { get; set; }
        public string LocalEmIE { get; set; }
        public Nullable<System.DateTime> DataEmIE { get; set; }
        public Nullable<System.DateTime> DataValidadeIE { get; set; }
        public Nullable<System.Guid> CodSeguro { get; set; }
        public Nullable<System.DateTime> DataInicioBonificacao { get; set; }
        public Nullable<System.DateTime> DataFimBonificacao { get; set; }
        public string TipoRendimento { get; set; }
        public string GrupoTraco { get; set; }
        public double MinPessoalFamiliar { get; set; }
        public short Regime { get; set; }
        public Nullable<decimal> BaseCotizacao { get; set; }
        public decimal CustoPadrao { get; set; }
        public bool UtilizadoCCOP { get; set; }
        public Nullable<int> RecursoCCOP { get; set; }
        public bool Isento { get; set; }
        public string PercVencParaSubsFerias { get; set; }
        public string PercVencParaSubsNatal { get; set; }
        public Nullable<bool> EmprestimoBancario { get; set; }
        public Nullable<bool> EmprestimoBancarioAntesRegul { get; set; }
        public double ValorAbateAntesRegul { get; set; }
        public double RetribAnuaisIniciais { get; set; }
        public string MotivoAdmissao { get; set; }
        public string PrimeiroNome { get; set; }
        public string PrimeiroApelido { get; set; }
        public string SegundoApelido { get; set; }
        public string ContribuinteNaoResidente { get; set; }
        public string AplicabilidadeIRCT { get; set; }
        public Nullable<int> CategoriaEscalao { get; set; }
        public Nullable<short> MesSubsNatal { get; set; }
        public string FormaPagSN { get; set; }
        public string FormaPagSF { get; set; }
        public bool ProcDiasAnterioresSN { get; set; }
        public bool ProcDiasAnterioresSF { get; set; }
        public string CodAlimDiasProc { get; set; }
        public string CodAlimValorFixo { get; set; }
        public string CodAlimEspecie { get; set; }
        public string TabIRPS { get; set; }
        public bool LigadoTimesheets { get; set; }
        public string Pais { get; set; }
        public string ADSE { get; set; }
        public Nullable<bool> AguardarAposentacao { get; set; }
        public Nullable<int> AnosFuncaoPublica { get; set; }
        public Nullable<bool> ComprovativoGravidez { get; set; }
        public Nullable<System.DateTime> DataAposentacao { get; set; }
        public Nullable<System.DateTime> DataDespachoDR { get; set; }
        public Nullable<System.DateTime> DataGravidez { get; set; }
        public Nullable<System.DateTime> DataInicioAdmPub { get; set; }
        public Nullable<System.DateTime> DataInicioCategoria { get; set; }
        public Nullable<System.DateTime> DataInicioEscalao { get; set; }
        public Nullable<System.DateTime> DataValidadeADSE { get; set; }
        public string DiarioRepublica { get; set; }
        public Nullable<int> DiasFuncaoPublica { get; set; }
        public Nullable<int> DiasNaCategoria { get; set; }
        public Nullable<int> DiasNoEscalao { get; set; }
        public Nullable<bool> DireitoSubsidioPreNatal { get; set; }
        public string EducacaoFuncao { get; set; }
        public string EducacaoSituacao { get; set; }
        public Nullable<int> Escalao { get; set; }
        public Nullable<bool> InactivoTemp { get; set; }
        public Nullable<int> Indice { get; set; }
        public Nullable<int> MesesFuncaoPublica { get; set; }
        public string MotivoMC { get; set; }
        public string NivelRemuneratorio { get; set; }
        public string NumADSE { get; set; }
        public Nullable<int> NumeroNaciturnos { get; set; }
        public Nullable<double> PercentIndice100 { get; set; }
        public string ProcessoExecucao { get; set; }
        public string RegimeIndice100 { get; set; }
        public string TabelaIrsAposentacao { get; set; }
        public Nullable<byte> TipoBalancoSocial { get; set; }
        public string Utilizador { get; set; }
        public Nullable<double> ValorDifPosicaoRemun { get; set; }
        public Nullable<double> ValorMensalAposentacao { get; set; }
        public string ModContratoCom { get; set; }
        public Nullable<System.DateTime> DataComunicacao { get; set; }
        public string UtilizadorComunicacao { get; set; }
        public string CartaoResidente { get; set; }
        public Nullable<System.DateTime> DataEmissaoCR { get; set; }
        public Nullable<System.DateTime> DataValidadeCR { get; set; }
        public string LocalEmCR { get; set; }
        public Nullable<short> TipoMoeda { get; set; }
        public string IdentContrFundos { get; set; }
        public Nullable<System.DateTime> DataComFundos { get; set; }
        public Nullable<System.DateTime> DataCessaFundos { get; set; }
        public string MotivoCessaFundos { get; set; }
        public Nullable<System.DateTime> DataComAltVencFundos { get; set; }
        public Nullable<byte> RegimeExRes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncAgregadoFamiliar> FuncAgregadoFamiliar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncHorarios> FuncHorarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncInfFerias> FuncInfFerias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncInfNatal> FuncInfNatal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncInfSFerias> FuncInfSFerias { get; set; }
        public virtual Apolices Apolices { get; set; }
        public virtual Bonificacoes Bonificacoes { get; set; }
        public virtual Cargos Cargos { get; set; }
        public virtual Categorias Categorias { get; set; }
        public virtual CategoriasEscaloes CategoriasEscaloes { get; set; }
        public virtual ContratosTrabalho ContratosTrabalho { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual Estabelecimentos Estabelecimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncFormasPagamento> FuncFormasPagamento { get; set; }
        public virtual GruposCotizacao GruposCotizacao { get; set; }
        public virtual Habilitacoes Habilitacoes { get; set; }
        public virtual Instrumentos Instrumentos { get; set; }
        public virtual Moedas Moedas { get; set; }
        public virtual MotivosAdmissao MotivosAdmissao { get; set; }
        public virtual MotivosSaida MotivosSaida { get; set; }
        public virtual Nacionalidades Nacionalidades { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual Profissoes Profissoes { get; set; }
        public virtual RegimesTrabalho RegimesTrabalho { get; set; }
        public virtual RepFinancas RepFinancas { get; set; }
        public virtual SegSocial SegSocial { get; set; }
        public virtual Sindicatos Sindicatos { get; set; }
        public virtual SituacoesCGA SituacoesCGA { get; set; }
        public virtual TiposPessoal TiposPessoal { get; set; }
        public virtual TiposRendimento TiposRendimento { get; set; }
        public virtual TurnosHoras TurnosHoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncRem> FuncRem { get; set; }
    }
}
