//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncRem
    {
        public string Funcionario { get; set; }
        public string Remuneracao { get; set; }
        public Nullable<double> Valor { get; set; }
        public short AnoInicial { get; set; }
        public short AnoFinal { get; set; }
        public short PeriodoInicial { get; set; }
        public short PeriodoFinal { get; set; }
        public Nullable<float> Quantidade { get; set; }
        public Nullable<double> ValorUnitario { get; set; }
        public System.Guid idFuncRemCBL { get; set; }
        public Nullable<System.DateTime> DataViat { get; set; }
    
        public virtual Funcionarios Funcionarios { get; set; }
    }
}
