//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncInfSFerias
    {
        public short Ano { get; set; }
        public string Funcionario { get; set; }
        public Nullable<float> DiasDireito { get; set; }
        public Nullable<float> DiasAdicionais { get; set; }
        public Nullable<float> DiasAnoAnterior { get; set; }
        public Nullable<float> TotalDias { get; set; }
        public Nullable<float> DiasPorPagar { get; set; }
        public Nullable<float> DiasJaPagos { get; set; }
        public bool FuncSemSFerias { get; set; }
        public Nullable<float> DiasSubsFAbater { get; set; }
        public Nullable<bool> Fixo { get; set; }
        public Nullable<float> DiasTransitados { get; set; }
    
        public virtual Funcionarios Funcionarios { get; set; }
    }
}
