//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncFormasPagamento
    {
        public System.Guid ID { get; set; }
        public string Funcionario { get; set; }
        public bool Activo { get; set; }
        public short Forma { get; set; }
        public string Moeda { get; set; }
        public double Percentagem { get; set; }
        public string ContaEmpresa { get; set; }
        public string Banco { get; set; }
        public string Balcao { get; set; }
        public string NumConta { get; set; }
        public string NIB { get; set; }
        public string IBAN { get; set; }
        public string SWIFT { get; set; }
        public string BIC { get; set; }
        public bool Default { get; set; }
        public string CartaoBancario { get; set; }
        public string Remuneracao { get; set; }
        public string ModoPagTesouraria { get; set; }
        public string ContaDomiciliacao { get; set; }
    
        public virtual Funcionarios Funcionarios { get; set; }
        public virtual Moedas Moedas { get; set; }
    }
}
