//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRIPRHEntities : DbContext
    {
        public PRIPRHEntities()
            : base("name=PRIPRHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FuncAgregadoFamiliar> FuncAgregadoFamiliar { get; set; }
        public virtual DbSet<FuncHorarios> FuncHorarios { get; set; }
        public virtual DbSet<FuncInfFerias> FuncInfFerias { get; set; }
        public virtual DbSet<FuncInfNatal> FuncInfNatal { get; set; }
        public virtual DbSet<FuncInfSFerias> FuncInfSFerias { get; set; }
        public virtual DbSet<Funcionarios> Funcionarios { get; set; }
        public virtual DbSet<Apolices> Apolices { get; set; }
        public virtual DbSet<Bonificacoes> Bonificacoes { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<CategoriasEscaloes> CategoriasEscaloes { get; set; }
        public virtual DbSet<ContratosTrabalho> ContratosTrabalho { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Estabelecimentos> Estabelecimentos { get; set; }
        public virtual DbSet<FuncFormasPagamento> FuncFormasPagamento { get; set; }
        public virtual DbSet<FuncRem> FuncRem { get; set; }
        public virtual DbSet<GruposCotizacao> GruposCotizacao { get; set; }
        public virtual DbSet<Habilitacoes> Habilitacoes { get; set; }
        public virtual DbSet<Instrumentos> Instrumentos { get; set; }
        public virtual DbSet<Moedas> Moedas { get; set; }
        public virtual DbSet<MotivosAdmissao> MotivosAdmissao { get; set; }
        public virtual DbSet<MotivosSaida> MotivosSaida { get; set; }
        public virtual DbSet<Nacionalidades> Nacionalidades { get; set; }
        public virtual DbSet<Ocorrencias> Ocorrencias { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Profissoes> Profissoes { get; set; }
        public virtual DbSet<RegimesTrabalho> RegimesTrabalho { get; set; }
        public virtual DbSet<RepFinancas> RepFinancas { get; set; }
        public virtual DbSet<SegSocial> SegSocial { get; set; }
        public virtual DbSet<Sindicatos> Sindicatos { get; set; }
        public virtual DbSet<SituacoesCGA> SituacoesCGA { get; set; }
        public virtual DbSet<SituacoesGAB> SituacoesGAB { get; set; }
        public virtual DbSet<SobretaxaIRS> SobretaxaIRS { get; set; }
        public virtual DbSet<TiposAusencia> TiposAusencia { get; set; }
        public virtual DbSet<TiposFaltas> TiposFaltas { get; set; }
        public virtual DbSet<TiposHorarios> TiposHorarios { get; set; }
        public virtual DbSet<TiposPessoal> TiposPessoal { get; set; }
        public virtual DbSet<TiposRecursos> TiposRecursos { get; set; }
        public virtual DbSet<TiposRendimento> TiposRendimento { get; set; }
        public virtual DbSet<TurnosHoras> TurnosHoras { get; set; }
    }
}
