//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moedas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moedas()
        {
            this.Apolices = new HashSet<Apolices>();
            this.FuncFormasPagamento = new HashSet<FuncFormasPagamento>();
            this.Funcionarios = new HashSet<Funcionarios>();
            this.Sindicatos = new HashSet<Sindicatos>();
        }
    
        public string Moeda { get; set; }
        public string Descricao { get; set; }
        public Nullable<double> Compra { get; set; }
        public Nullable<double> Venda { get; set; }
        public Nullable<System.DateTime> DataCambio { get; set; }
        public Nullable<bool> PertenceUEM { get; set; }
        public Nullable<int> DecArredonda { get; set; }
        public string DescParteInteira { get; set; }
        public string DescParteDecimal { get; set; }
        public Nullable<short> DecArredondaIva { get; set; }
        public Nullable<short> DecPrecUnit { get; set; }
        public Nullable<System.DateTime> DataUltimaActualizacao { get; set; }
        public byte[] VersaoUltAct { get; set; }
        public string IDIso { get; set; }
        public string Simbolo { get; set; }
        public string ISO4217 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apolices> Apolices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncFormasPagamento> FuncFormasPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sindicatos> Sindicatos { get; set; }
    }
}
