//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivosSaida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotivosSaida()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
            this.Instrumentos = new HashSet<Instrumentos>();
        }
    
        public string MotivoSaida { get; set; }
        public string Descricao { get; set; }
        public Nullable<byte> MotivoBS { get; set; }
        public string Situacao { get; set; }
        public Nullable<bool> ExigeAvisoPrevio { get; set; }
        public Nullable<bool> AvisoPrevioFunc { get; set; }
        public Nullable<bool> AvisoPrevioEmp { get; set; }
        public Nullable<bool> PagaAvisoPrevio { get; set; }
        public Nullable<bool> PagaSalarios { get; set; }
        public Nullable<bool> PagaCompensacao { get; set; }
        public Nullable<bool> PagaIndDesped { get; set; }
        public Nullable<bool> PagaDespedFunc { get; set; }
        public Nullable<bool> PagaDespedEmp { get; set; }
        public Nullable<byte> FormulaIndDesp { get; set; }
        public Nullable<byte> FormulaIndAvisoPrev { get; set; }
        public Nullable<byte> FormulaCompensacaoCaducid { get; set; }
        public string CodigoRelUnico { get; set; }
        public string CodigoMotivoCE { get; set; }
        public Nullable<bool> Acumulativo { get; set; }
        public byte TipoBalancoSocial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instrumentos> Instrumentos { get; set; }
    }
}
