//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sindicatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sindicatos()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
        }
    
        public string Sindicato { get; set; }
        public string Descricao { get; set; }
        public bool Percentagem { get; set; }
        public Nullable<float> Valor { get; set; }
        public string ContrColetivo { get; set; }
        public Nullable<System.DateTime> DataContrato { get; set; }
        public Nullable<float> ValorMin { get; set; }
        public bool PagoVencimento { get; set; }
        public bool PagoMesFerias { get; set; }
        public bool PagoSubsNatal { get; set; }
        public bool PagoSubsFerias { get; set; }
        public bool PagoExtra { get; set; }
        public string EnderecoWeb { get; set; }
        public string Email { get; set; }
        public string Morada { get; set; }
        public string Localidade { get; set; }
        public string Cp { get; set; }
        public string CpLoc { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string NumContrib { get; set; }
        public string Moeda { get; set; }
        public string ModoPagamentoCCT { get; set; }
        public string TipoEntidadeCCT { get; set; }
        public string EntidadeCCT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
        public virtual Moedas Moedas { get; set; }
    }
}
