//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SituacoesCGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SituacoesCGA()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
            this.TiposAusencia = new HashSet<TiposAusencia>();
        }
    
        public string Situacao { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> ObDataEfeito { get; set; }
        public Nullable<bool> ObRemuneracao { get; set; }
        public Nullable<bool> ObDesconto { get; set; }
        public Nullable<bool> ObPerdaEfectividade { get; set; }
        public Nullable<bool> ObHorarioParcial { get; set; }
        public Nullable<bool> ObNDiuturnidades { get; set; }
        public Nullable<bool> ObCategoria { get; set; }
        public Nullable<bool> ObNivelRem { get; set; }
        public Nullable<bool> ObPercAcrescida { get; set; }
        public Nullable<int> TipoSituacao { get; set; }
        public Nullable<byte> PosGuia { get; set; }
        public Nullable<bool> SituacaoActiva { get; set; }
        public Nullable<bool> NumeroDiasTrabalho { get; set; }
        public Nullable<bool> HorarioCompleto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposAusencia> TiposAusencia { get; set; }
    }
}
