//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SobretaxaIRS
    {
        public short NLinha { get; set; }
        public string Desconto { get; set; }
        public System.DateTime DataInicial { get; set; }
        public System.DateTime DataFinal { get; set; }
        public double Valor { get; set; }
        public double Percentagem { get; set; }
        public short DomicilioFiscal { get; set; }
        public short Tabela { get; set; }
        public short Filhos { get; set; }
    }
}
