//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposHorarios
    {
        public string TipoHorario { get; set; }
        public string Descricao { get; set; }
        public string ColunaQP { get; set; }
        public Nullable<short> PosBS { get; set; }
        public Nullable<short> PosSHST { get; set; }
        public string CodigoRelUnico { get; set; }
        public byte TipoBalancoSocial { get; set; }
    }
}
