//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposAusencia
    {
        public string Ausencia { get; set; }
        public string Descricao { get; set; }
        public Nullable<short> TipoAusencia { get; set; }
        public Nullable<bool> TemCompBaixa { get; set; }
        public string Falta { get; set; }
        public string SituacaoCGA { get; set; }
        public string RemPagamento { get; set; }
        public string RemAdiantamento { get; set; }
        public Nullable<short> TipoBaseReguladora { get; set; }
        public Nullable<bool> DataRecibo { get; set; }
        public string DescricaoRecibo { get; set; }
        public Nullable<int> LimiteDias { get; set; }
        public Nullable<double> LimitePercentagem { get; set; }
        public Nullable<double> MontanteMaximo { get; set; }
        public Nullable<double> MontanteMinimo { get; set; }
        public string MotivoNE { get; set; }
        public Nullable<short> NDiasInicial { get; set; }
        public Nullable<bool> NumeroDiasRecibo { get; set; }
        public Nullable<bool> PagaComplemento { get; set; }
        public float PercAdiant { get; set; }
        public Nullable<float> PercInicialPag { get; set; }
        public Nullable<float> PercRestantePag { get; set; }
        public Nullable<int> TipoDiasAusencia { get; set; }
        public Nullable<int> TipoRefMaximo { get; set; }
        public Nullable<int> TipoRefMinimo { get; set; }
        public Nullable<int> TipoRefPercentagem { get; set; }
        public Nullable<int> TipoRefPercMaximo { get; set; }
        public Nullable<int> TipoRefPercMinimo { get; set; }
        public Nullable<short> TipoSituacao { get; set; }
        public Nullable<int> ValorRemuneracaoMedia { get; set; }
    
        public virtual SituacoesCGA SituacoesCGA { get; set; }
    }
}
