//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDRequisicao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtigoMoeda
    {
        public string Artigo { get; set; }
        public string Moeda { get; set; }
        public Nullable<double> PVP1 { get; set; }
        public Nullable<double> PVP2 { get; set; }
        public Nullable<double> PVP3 { get; set; }
        public Nullable<double> PVP4 { get; set; }
        public Nullable<double> PVP5 { get; set; }
        public Nullable<double> PVP6 { get; set; }
        public byte[] VersaoUltAct { get; set; }
        public string Unidade { get; set; }
        public bool PVP1IvaIncluido { get; set; }
        public bool PVP2IvaIncluido { get; set; }
        public bool PVP3IvaIncluido { get; set; }
        public bool PVP4IvaIncluido { get; set; }
        public bool PVP5IvaIncluido { get; set; }
        public bool PVP6IvaIncluido { get; set; }
    
        public virtual Artigo Artigo1 { get; set; }
    }
}
