//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDRequisicao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artigo()
        {
            this.Artigo11 = new HashSet<Artigo>();
            this.ArtigoMoeda = new HashSet<ArtigoMoeda>();
        }
    
        public string Artigo1 { get; set; }
        public string Descricao { get; set; }
        public string CodBarras { get; set; }
        public string UnidadeVenda { get; set; }
        public string UnidadeBase { get; set; }
        public string Iva { get; set; }
        public Nullable<float> Desconto { get; set; }
        public string Fornecedor { get; set; }
        public Nullable<double> STKMinimo { get; set; }
        public Nullable<double> STKMaximo { get; set; }
        public Nullable<double> STKReposicao { get; set; }
        public Nullable<double> STKActual { get; set; }
        public Nullable<double> PCMedio { get; set; }
        public Nullable<double> PCUltimo { get; set; }
        public string MovStock { get; set; }
        public Nullable<System.DateTime> DataUltEntrada { get; set; }
        public Nullable<System.DateTime> DataUltSaida { get; set; }
        public string Familia { get; set; }
        public string ArtSubstituto { get; set; }
        public string ArtAssociado { get; set; }
        public string ArmazemSugestao { get; set; }
        public string TipoArtigo { get; set; }
        public Nullable<short> TipoComponente { get; set; }
        public bool NecessarioRecalcPCM { get; set; }
        public Nullable<double> PCPadrao { get; set; }
        public Nullable<short> SugestaoPrComposto { get; set; }
        public Nullable<double> UltDescontoComercialCompra { get; set; }
        public Nullable<double> UltDespesaAdicionalCompra { get; set; }
        public Nullable<short> PrazoEntrega { get; set; }
        public Nullable<double> QtdEconomica { get; set; }
        public string FormulaVendas { get; set; }
        public string UltimoFornecedor { get; set; }
        public string SubFamilia { get; set; }
        public string UltimoTipoDoc { get; set; }
        public Nullable<int> UltimoNumDoc { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Volume { get; set; }
        public string Marca { get; set; }
        public string Garantia { get; set; }
        public bool ArtigoAnulado { get; set; }
        public bool TratamentoSeries { get; set; }
        public bool TratamentoLotes { get; set; }
        public bool LoteFormulaEntradas { get; set; }
        public string LoteEntradas { get; set; }
        public bool LoteFormulaSaidas { get; set; }
        public string LoteSaidas { get; set; }
        public string FormulaCompras { get; set; }
        public string UltimoNumSerie { get; set; }
        public string UltimoLote { get; set; }
        public string IntrastatPautal { get; set; }
        public Nullable<double> IntrastatPeso { get; set; }
        public Nullable<System.DateTime> DataUltimaActualizacao { get; set; }
        public bool TestaNumSerie { get; set; }
        public bool SujeitoRetencao { get; set; }
        public string Observacoes { get; set; }
        public string TipoDim1 { get; set; }
        public string TipoDim2 { get; set; }
        public string TipoDim3 { get; set; }
        public string Dim1 { get; set; }
        public string Dim2 { get; set; }
        public string Dim3 { get; set; }
        public bool DimLote { get; set; }
        public short TratamentoDim { get; set; }
        public string Etiqueta { get; set; }
        public byte[] VersaoUltAct { get; set; }
        public bool OperacaoTesouraria { get; set; }
        public string EntidadeOPTesouraria { get; set; }
        public string Modelo { get; set; }
        public string UnidadeCompra { get; set; }
        public string UnidadeEntrada { get; set; }
        public string UnidadeSaida { get; set; }
        public string UltimaSerieDoc { get; set; }
        public bool DeduzIvaNoImo { get; set; }
        public bool PermiteDevolucao { get; set; }
        public string TipoEntidadeOpTesouraria { get; set; }
        public bool Imposto { get; set; }
        public string TipoDocOpTesouraria { get; set; }
        public bool UtilizadoCCOP { get; set; }
        public bool Pesar { get; set; }
        public Nullable<System.Guid> IdGDOC { get; set; }
        public bool SujeitoProRata { get; set; }
        public Nullable<float> PercIvaDedutivel { get; set; }
        public bool SujeitoEcotaxa { get; set; }
        public Nullable<double> Ecovalor { get; set; }
        public bool AfectaPCM { get; set; }
        public string LocalizacaoSugestao { get; set; }
        public string ArtigoPai { get; set; }
        public Nullable<int> OrdemDim { get; set; }
        public string RubDim1 { get; set; }
        public string RubDim2 { get; set; }
        public string RubDim3 { get; set; }
        public Nullable<byte> IDTipoOrigemGPR { get; set; }
        public bool FabCompAutoGPR { get; set; }
        public bool CalcNecessidadesGPR { get; set; }
        public Nullable<float> QtReservadaGPR { get; set; }
        public Nullable<float> QtReceberGPR { get; set; }
        public Nullable<byte> IDTipoProducaoGPR { get; set; }
        public Nullable<float> DesperdicioGPR { get; set; }
        public bool UtilizadoGPR { get; set; }
        public Nullable<double> PercIncidenciaIVA { get; set; }
        public Nullable<int> NaturezaAnalitica { get; set; }
        public Nullable<System.Guid> IdClassificacao { get; set; }
        public string FormulaGPR { get; set; }
        public Nullable<int> SequenciaGPR { get; set; }
        public string CDU_CampoVar1 { get; set; }
        public string CDU_CampoVar2 { get; set; }
        public string CDU_CampoVar3 { get; set; }
        public Nullable<bool> DesactivadoGPR { get; set; }
        public Nullable<System.DateTime> DataDesactivacaoGPR { get; set; }
        public Nullable<bool> SujeitoIEC { get; set; }
        public string CategoriaIEC { get; set; }
        public string CodigoTaric { get; set; }
        public string EmbalagemIEC { get; set; }
        public Nullable<double> CapacidadeEmbIEC { get; set; }
        public string UnidadeTaric { get; set; }
        public Nullable<double> FactConvIEC { get; set; }
        public Nullable<double> ValorIEC { get; set; }
        public Nullable<double> TaxaAlcool { get; set; }
        public Nullable<bool> UtilManutencao { get; set; }
        public Nullable<double> PesoLiquido { get; set; }
        public bool GestaoSingular { get; set; }
        public string Selo { get; set; }
        public string CodigoBebidaEspirituosa { get; set; }
        public string CodigoEstampilha { get; set; }
        public float FactorUnidadeSup { get; set; }
        public string GrupoCenariosCompras { get; set; }
        public bool IsentoPagDireitos { get; set; }
        public string CodigoPautal { get; set; }
        public Nullable<bool> ControlaTransformacaoValor { get; set; }
        public string CodigoCPV { get; set; }
        public bool IsentoIEC { get; set; }
        public string CodigoIsentoIEC { get; set; }
        public byte TipoCusteio { get; set; }
        public Nullable<System.Guid> IdTransferencia { get; set; }
        public Nullable<System.DateTime> DataTransferencia { get; set; }
        public Nullable<System.DateTime> DataCustoPadrao { get; set; }
        public Nullable<int> CodigoAdicionalAltIEC { get; set; }
        public Nullable<bool> SujeitoRetencaoArtigo { get; set; }
        public Nullable<double> RetencaoArtigoValor { get; set; }
        public Nullable<bool> RetencaoArtigoTipoValor { get; set; }
        public string eGAR_LER { get; set; }
        public string eGAR_Grupo { get; set; }
        public string NumeroONU { get; set; }
        public string GrupoEmbalagem { get; set; }
        public string ClasseArtigoTaxFree { get; set; }
        public Nullable<System.DateTime> LastIndexDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artigo> Artigo11 { get; set; }
        public virtual Artigo Artigo2 { get; set; }
        public virtual Familias Familias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtigoMoeda> ArtigoMoeda { get; set; }
    }
}
