//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDRequisicao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRIPOWERBIEntities : DbContext
    {
        public PRIPOWERBIEntities()
            : base("name=PRIPOWERBIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artigo> Artigo { get; set; }
        public virtual DbSet<ArtigoMoeda> ArtigoMoeda { get; set; }
        public virtual DbSet<Familias> Familias { get; set; }
        public virtual DbSet<V_Entidades> V_Entidades { get; set; }
    }
}
